# Cross-validation {#origami}

## Introduction

### Roadmap Review
### We want to fit the data to estimate Q
### We can propose and test models

## Learning Objectives

By the end of this chapter you will be able to:

1. Differentiate between training, validation and test sets.
2. Understand the concept of a loss function, risk and cross-validation.
3. Select a loss function that is appropriate for the functional parameter to be
   estimated.
4. Understand and contrast different cross-validation schemes for i.i.d. data.
5. Understand and contrast different cross-validation schemes for time dependent
   data.
6. Setup the proper fold structure, build custom fold-based function, and
   cross-validate the proposed function using the `origami` `R` package.
7. Setup the proper cross-validation structure for the use by the Super Learner
   using the the `origami` `R` package.

## schematic example
### show overfit on test set
### show cross-validation

## Conceptual

## washb example

## advanced usage